name: 'Test PR Title'

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  test-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Conventional PR Title Checker
        uses: aslafy-z/conventional-pr-title-action@master
        with:
          success-state: PR title follows the standard
          failure-state: Please conform to PR title standard
          preset: conventional-changelog-angular@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}